<?php return array(
  'prime' => 1,
  'vip' => 1,
  'admin' => 1,
  'panel' => 0,
  'type' => 0,
  'time' => '30',
  'plugs' => 1,
  'filter_modes' => 1,
  'server_card_count' => '2',
  'punish_all_server' => 1,
  'server_table_count' => '2',
  'enable_mods' => 0,
  'enable_emptys' => 1,
  'grid_counts' => '1',
  'password' => '',
  'debug' => 0,
  'centered_mods' => 0,
  'server_counter' => 1,
  'mon_button' => 0,
  'excluded_admins' =>
  array(),
  'show_ping' => 1,
  'show_online_line' => 1,
);
